language: generic
sudo: required
services:
  - docker

berfore_install:
  - docker build -t ruslaniv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ruslaniv/docker-react npm run test
