language: generic
dist: focal
os: linux
services:
  - docker

before_install:
  - docker build -t ruslaniv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ruslaniv/docker-react npm run test
